#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from solver import solver
from problems import Solitaire

# get arguments
if len(sys.argv) == 2:
    fsol = file(sys.argv[1], 'r')
    lines = fsol.readlines()
    board_size = int(lines[0])
    board = []
    for line in lines[1:]:
        try:
            row = map(int, line[:-1].split())
            if filter(lambda x: x < 0 or x > 2, row) or len(row) != board_size:
                raise ValueError
            board.extend(row)
        except ValueError:
            print 'Formato erróneo, saliendo...'
            sys.exit(0)
else:
    try:
        board_size = int(raw_input('Introduzca el tamaño del tablero: '))
        if board_size < 1:
            raise ValueError
    except ValueError:
        print 'El tamaño del tablero debe ser un número positivo'
        sys.exit(0)

    print """
    Introduzca la configuración del tablero. Si ésta no esta especificada como
    en el enunciado del proyecto, el programa terminará.
    """

    board = []
    for i in range(0, board_size):
        inp = raw_input('')
        try:
            row = map(int, inp.split())
            if filter(lambda x: x < 0 or x > 2, row) or len(row) != board_size:
                raise ValueError
            board.extend(row)
        except ValueError:
            print 'Formato erróneo, saliendo...'
            sys.exit(0)
# ...

solver(Solitaire, board_size=board_size, board=board)
